services:
  - type: web
    name: graduation-invitation
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: NEXT_PUBLIC_EVENT_NAME
        value: "Nhat's graduation"
      - key: NEXT_PUBLIC_EVENT_DATE
        value: "2025-11-27"
      - key: NEXT_PUBLIC_EVENT_TIME
        value: "11:30"
      - key: NEXT_PUBLIC_EVENT_LOCATION
        value: "Sảnh A - Trường Đại học Công nghệ thông tin (ĐHQG-TPHCM)"
      - key: NEXT_PUBLIC_EVENT_ADDRESS
        value: "Khu Phố 6, Linh Trung, Thủ Đức, TP. Hồ Chí Minh"

